pipeline { 
    agent any 
    stages {
        stage('Build') { 
            steps { 
		checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/vue07418/Calavera2.git']]])
                sh 'docker build -t lars2804/nde-web-app .' 
            }
        }
    }
}

