pipeline { 
	agent any
	
        stages {
               stage('Clone repository') { 
                        steps { 
		                git 'https://github.com/vue07418/Calavera2.git'
			}
		}
     
        }
	
}

