pipeline { 
    agent { dockerfile true } 
    stages {
        stage('Clone repository') { 
            steps { 
		checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/vue07418/Calavera2.git']]])
               
            }

        stage('Build image') {
	    steps {
		app = docker.build("Calavera2/201802/07")
	    }
        }
      }
    }
}

